image: python:3.6

cache:
  paths:
    - .pip

stages:
  - test_lint
  - build
  - deploy

test-unit-and-lint:
  stage: test_lint
  script:
    - mkdir -p .pip
    - pip install -U pip
    - pip --cache-dir=.pip install -r requirements.txt
    - pytest .
    - flake8 .

build-and-run-pipeline:
  stage: build
  tags:
    - deploy-leuchtturm-cluster
  script:
    - export PATH=~/anaconda2/bin:$PATH
    - conda create -n leuchtturm_env python=3.6 -y --copy || true
    - source activate leuchtturm_env
    - ./tests/test_integration_pipeline.sh
    - source deactivate
  artifacts:
    paths:
      - result.txt
    expire_in: 2 weeks
    
deploy-sopedu-master:
  stage: deploy
  when: manual
  tags:
    - deploy-sopedu-cluster
  script:
    - export PATH=~/anaconda2/bin:$PATH
    - export SPARK_HOME=/usr/hdp/2.6.2.0-205/spark2/
    - ./deploy_sopedu_pipeline.sh master
  environment:
    name: sopedu_pipeline_master
    url: http://sopedu.hpi.uni-potsdam.de:8983/solr/#/enron

deploy-sopedu-dev:
  stage: deploy
  when: manual
  tags:
    - deploy-sopedu-cluster
  script:
    - export PATH=~/anaconda2/bin:$PATH
    - export SPARK_HOME=/usr/hdp/2.6.2.0-205/spark2/
    - ./deploy_sopedu_pipeline.sh dev
  environment:
    name: sopedu_pipeline_dev
    url: http://sopedu.hpi.uni-potsdam.de:8983/solr/#/enron_dev

# deploy-sopedu-mr:
#   stage: deploy
#   only:
#     - web
#   tags:
#     - deploy-sopedu-cluster
#   script:
#     - export PATH=~/anaconda2/bin:$PATH
#     - export SPARK_HOME=/usr/hdp/2.6.2.0-205/spark2/
#     - ./deploy_sopedu_pipeline.sh mr
#   environment:
#     name: sopedu_pipeline_mr
#     url: http://sopedu.hpi.uni-potsdam.de:8983/solr/#/pipeline_mr
