image: continuumio/miniconda3:latest

before_script:
  - conda env create -f environment.yml
  - source activate pipeline

stages:
  - test_and_lint
  - codequality

test:
  stage: test_and_lint
  script:
    - flake8 .

lint:
  stage: test_and_lint
  script:
    - pytest

codequality:
  image: coala/base
  stage: codequality
  script:
    - coala --ci
