image: python

stages:
  - codequality
  - test_and_lint

test_and_lint:
  stage: test_and_lint
  script:
    - pip install -r requirements.txt
    - flake8 . # this also runs pydocstyle linting as a plugin of flake8 (see requirements.txt)
    - pytest

codeclimate_analysis:
  stage: codequality
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - pwd
    - ls -alt
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:latest analyze structure
  artifacts:
    paths: [codeclimate.json]