image: python

stages:
  - test_and_lint
  - codequality

test_and_lint:
  stage: test_and_lint
  script:
    - pip install -r requirements.txt
    - flake8 . # this also runs pydocstyle linting as a plugin of flake8 (see requirements.txt)
    - pytest

codequality:
  image: coala/base
  stage: codequality
  script:
    - pip install -r requirements.txt
    - coala --ci
