image: python:3.6

cache:
  paths:
    - .pip

stages:
  - deploy
  - test_and_lint
  - codequality

lint:
  stage: test_and_lint
  script:
    - mkdir -p .pip
    - pip install -U pip
    - pip --cache-dir=.pip install -r requirements.txt
    - flake8 .

test:
  stage: test_and_lint
  script:
    - mkdir -p .pip
    - pip install -U pip
    - pip --cache-dir=.pip install -r requirements.txt
    - pytest

codequality:
  image: coala/base
  stage: codequality
  script:
    - echo "Find code smells..."
    - coala -I --ci --files=\*\*/\*.py --ignore=src/emailbody\*\*/\*.py --bears=RadonBear,PyCommentedCodeBear,PySafetyBear,PyUnusedCodeBear,VultureBear
    
deploy-leuchtturm-cluster:
  stage: deploy
  tags:
    - deploy-leuchtturm-cluster
  script:
    - cat ~/.bashrc
    - conda create -n leuchtturm_env python=3.6 -y || true
    - source activate leuchtturm_env
    - pip install -r requirements.txt -y
