image: python

stages:
  - codequality
  - test_and_lint

test_and_lint:
  stage: test_and_lint
  script:
    - pip install -r requirements.txt
    - flake8 . # this also runs pydocstyle linting as a plugin of flake8 (see requirements.txt)
    - pytest

codequality:
  stage: codequality
  image: docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - export CODECLIMATE_DEBUG=1
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:latest analyze -e structure