image: python

stages:
  - test
  - codequality
  - build
  - deploy

lint_python:
  stage: test
  script:
    - pip install -r requirements.txt
    - flake8 . # this also runs pydocstyle linting as a plugin of flake8 (see requirements.txt)

test_python:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest

codequality:
  image: docker:dind
  script:
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:latest analyze -e structure duplication fixme git-legal radon markdownlint shellcheck structure -f json > codeclimate.json || true
  artifacts:
    paths: [codeclimate.json]