image: python:3.6

cache:
  paths:
    - .pip

stages:
  - test_unit
  - codequality
  - test_integration
  - deploy

# test:
#   stage: test_unit
#   script:
#     - mkdir -p .pip
#     - pip install -U pip
#     - pip --cache-dir=.pip install -r requirements.txt
#     - pytest --cov=src/ tests/
#   coverage: /\d+\%\s*$/

# lint:
#   stage: codequality
#   allow_failure: true
#   script:
#     - mkdir -p .pip
#     - pip install -U pip
#     - pip --cache-dir=.pip install -r requirements.txt
#     - flake8 .

# lint_strict:
#   stage: codequality
#   allow_failure: true
#   script:
#     - mkdir -p .pip
#     - pip install -U pip
#     - pip --cache-dir=.pip install flake8 mccabe flake8-print flake8-requirements flake8-bandit flake8-deprecated flake8-single-quotes flake8-todo
#     - flake8 . --max-complexity 10

pipeline-10-emails:
  stage: test_integration
  tags:
    - deploy-leuchtturm-cluster
  script:
    - export PATH=~/anaconda2/bin:$PATH
    - conda create -n leuchtturm_env python=3.6 -y --copy || true
    - source activate leuchtturm_env
    - pip install --quiet -r requirements.txt
    - ./test_integration_pipeline.sh
    - source deactivate
  artifacts:
    paths:
      - result.txt
    expire_in: 2 weeks
    
deploy-sopedu-master:
  stage: deploy
  # only:
  #   - master
  tags:
    - deploy-sopedu-cluster
  script:
    - export PATH=~/anaconda2/bin:$PATH
    - export SPARK_HOME=/usr/hdp/2.6.2.0-205/spark2/
    - ./deploy_pipeline.sh 2>/dev/null
  environment:
    name: sopedu_master
    url: http://sopedu.hpi.uni-potsdam.de:8983/solr/
  artifacts:
    paths:
      - result.txt
    expire_in: 2 weeks

deploy-sopedu-dev:
  stage: deploy
  only:
    - dev
  tags:
    - deploy-sopedu-cluster
  script:
    - export PATH=~/anaconda2/bin:$PATH
    - export SPARK_HOME=/usr/hdp/2.6.2.0-205/spark2/
    - ./deploy_pipeline.sh 2>/dev/null
  environment:
    name: sopedu_master
    url: http://sopedu.hpi.uni-potsdam.de:8983/solr/

deploy-sopedu-mr:
  stage: deploy
  only:
    - /^[deploy_sopedu_mr] /
  except:
    - branches
  tags:
    - deploy-sopedu-cluster
  script:
    - export PATH=~/anaconda2/bin:$PATH
    - export SPARK_HOME=/usr/hdp/2.6.2.0-205/spark2/
    - ./deploy_pipeline.sh 2>/dev/null
  environment:
    name: sopedu_master
    url: http://sopedu.hpi.uni-potsdam.de:8983/solr/
