image: python

stages:
  - test
  - codequality
  - build
  - deploy

lint_python:
  stage: test
  script:
    - pip install -r requirements.txt
    - flake8 . # this also runs pydocstyle linting as a plugin of flake8 (see requirements.txt)

test_python:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest

codequality:
  image: codeclimate/codeclimate
  script:
    - docker run codeclimate/codeclimate analyze -e duplication fixme git-legal radon markdownlint shellcheck structure -f json > codeclimate.json || true
  artifacts:
    paths: [codeclimate.json]