image: continuumio/miniconda3:latest

before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - conda env create -n pipeline -y python=3.6 anaconda
  - source activate pipeline
  - pip install -r requirements.txt

stages:
  - test_and_lint
  - codequality

test:
  stage: test_and_lint
  script:
    - flake8 .

lint:
  stage: test_and_lint
  script:
    - pytest

codequality:
  image: coala/base
  stage: codequality
  script:
    - coala --ci
