name: 'pipeline'

channels:
  - anaconda
  - conda-forge

dependencies:
  - python=3.6
  - pyspark
  - langdetect
  - neo4j-python-driver
  - hdfs3
  - pysolr
  - pytest
  - flake8
  - flake8-docstrings
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
    - apache-airflow
    - safygiphy
    - pytest-gitignore

